# --- METIN2 JIGSAW BOT KONFİGÜRASYONU  ---

# 1. SANDIK BUTONU (Parça Çekme)
OFF_BTN_CHEST = (227, 91)

# 2. ONAY BUTONLARI (Evet)
OFF_BTN_YES_ADD = (84, 86)
OFF_BTN_YES_DROP = (84, 86)

# 3. PARÇA TANIMA ALANI
OFF_PREVIEW = (0, 0)
PREVIEW_TOP_LEFT_OFFSET = (0, 0)